# Generated by Django 6.0.5 on 2026-05-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_id', models.IntegerField()),
                ('selger_id', models.IntegerField()),
                ('produkt_id', models.IntegerField(blank=True, null=True)),
                ('opprettet_tid', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Melding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avsender_id', models.IntegerField(blank=True, null=True)),
                ('tekst', models.TextField()),
                ('opprettet_tid', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meldinger', to='chat.chat')),
            ],
        ),
    ]
