# Generated by Django 6.0.5 on 2026-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('epost', models.EmailField(max_length=254, unique=True)),
                ('beskrivelse', models.TextField(blank=True)),
                ('rolle', models.CharField(choices=[('kunde', 'Kunde'), ('selger', 'Selger'), ('begge', 'Begge deler')], max_length=10)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
