# Generated by Django 5.2.5 on 2026-04-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('message', models.TextField(verbose_name='Melding')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-post')),
                ('status', models.CharField(choices=[('open', 'Åpen'), ('in_progress', 'Under behandling'), ('resolved', 'Løst'), ('closed', 'Lukket')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Lav'), ('medium', 'Medium'), ('high', 'Høy'), ('urgent', 'Akutt')], default='medium', max_length=20, verbose_name='Prioritet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oppdatert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hjelpeforespørsel',
                'verbose_name_plural': 'Hjelpeforespørsler',
                'ordering': ['-created_at'],
            },
        ),
    ]
